name: Trigger deploy of polaris.shopify.com

on:
  push:
    branches:
      - main
    paths:
      - 'polaris.shopify.com/**'
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch to deploy from'
        required: true
        default: 'main'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy polaris.shopify.com
        uses: actions/github-script@d7906e4ad0b1822421a7e6a35d5ca353c962f410 # v6.4.1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "shopify",
              repo: "polaris-site-prod-kit",
              workflow_id: "build-and-deploy.yml",
              ref: "{{ inputs.branch }}",
            });
