name: Trigger deploy of polaris.shopify.com

on:
  push:
    branches:
      - main
    paths:
      - 'polaris.shopify.com/**'

jobs:
  trigger-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger deploy polaris.shopify.com
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{ secrets.SHOPIFY_GH_ACCESS_TOKEN }}
          script: |
            await github.rest.actions.createWorkflowDispatch({
              owner: "shopify",
              repo: "polaris-site-prod-kit",
              workflow_id: "build-and-deploy.yml",
              ref: "main",
            });
